### ISSUE TITLE
Action's payload is implicitly sets to an array

### ISSUE THREAD

**Issue by irrvrsl** [atomixinteractions/redux-symbiote#14]
Hello! Is there a way to configure this behavior?

**Comment by irrvrsl** [comment]
I'm catching actions in redux-observable and every payload is an array. Currently I have to destructure payload to access an actual value. Even if i don't pass a value to an action creator it is initializing the payload with empty array.

**Comment by sergeysova** [comment]
What's behavior you need?

**Comment by irrvrsl** [comment]
It would be more predictable, if action creator will initialize payload on demand and set payload type as is.

https://github.com/atomixinteractions/redux-symbiote/blob/e5b7c2fed3f0abffcf7aa998db8c3e473b081f67/src/index.js#L4
This function might be written like:
```
const getActionCreatorDefault = (type) => (payload) => {
  const action = { type };
  
  if (payload !== undefined) {
    return Object.assign({}, action, { payload });
  }

  return action;
}
```

**Comment by sergeysova** [comment]
https://github.com/atomixinteractions/redux-symbiote/blob/master/src/index.js#L63

Are you suggesting to broke the API?

```js
// Before

createSymbiote(initialState, {
  foo: (state, arg1, arg2) => state,
})

foo(1, 2)
```


You suggest:

```js
createSymbiote(initialState, {
  // now we must have one argument
  foo: (state, { arg1, arg2 }) => state,
})

foo({ arg1: 1, arg2: 2 })
```

Am I correctly understand?

**Comment by sergeysova** [comment]
@irrvrsl If you don't use generated reducer, maybe, you don't need redux-symbiote.

See at [`redux-actions`](https://github.com/redux-utilities/redux-actions#usage). Maybe it solves your case.

**Comment by irrvrsl** [comment]
@sergeysova I'm using generated reducer as well. `redux-symbiote` have some advantages for me comparing with `redux-actions`(I've used that before), besides action creators. Maybe it's because I used to work with `redux-actions` API a lot. In most 'action handling' libraries action creators takes a `payload` for the first argument. Second can be a 'meta' and so on. That's why I was confused.

Anyway, I don't want to break an API and i don't see elegant solution to change existing one. Maybe you will consider to enhance your `options` later. Thanks for your time and a good library!

**Comment by yyynnn** [comment]
Yeah, that got me confused too. `payload[0]`. Maybe an option to set this to just `payload` would be so nice.

**Comment by sergeysova** [comment]
@yyynnn what about multiple arguments?

```js
const { actions } = createSymbiote({}, {
  example: (state, a, b) => ({ ...state, a, b })
})

actions.example(1, 2)
```

**Comment by sergeysova** [comment]
@yyynnn Are you use symbiote as action creator only?

**Comment by sergeysova** [comment]
What if I will refactor symbiote action generator:

```js
actions.namespace.name(1, 2, 3)
```

```json
{
  "type": "namespace/name",
  "payload": 1,
  "symbiote": [1, 2, 3]
}
```

**Comment by sergeysova** [comment]
@yyynnn @irrvrsl Try to use https://github.com/atomixinteractions/redux-symbiote/releases/tag/v3.0.0-0

**Comment by irrvrsl** [comment]
> @yyynnn @irrvrsl Try to use https://github.com/atomixinteractions/redux-symbiote/releases/tag/v3.0.0-0

Good job, i will give it a try on a new project👍

**Comment by yyynnn** [comment]
That was dope! Thank you Sova!
